response_data = {
  "device": {
    "id": "6393bce58cadea567d858c93c7998e6e92b55004",
    "is_active": true,
    "is_private_session": false,
    "is_restricted": false,
    "name": "Mart’s MacBook Pro",
    "type": "Computer",
    "volume_percent": 96
  },
  "shuffle_state": false,
  "repeat_state": "off",
  "timestamp": 1611450078549,
  "context": {
    "external_urls": {
      "spotify": "https://open.spotify.com/playlist/37i9dQZEVXbrJIES2PQPb0"
    },
    "href": "https://api.spotify.com/v1/playlists/37i9dQZEVXbrJIES2PQPb0",
    "type": "playlist",
    "uri": "spotify:user:spotify:playlist:37i9dQZEVXbrJIES2PQPb0"
  },
  "progress_ms": 26618,
  "item": {
    "album": {
      "album_type": "album",
      "artists": [
        {
          "external_urls": {
            "spotify": "https://open.spotify.com/artist/053q0ukIDRgzwTr4vNSwab"
          },
          "href": "https://api.spotify.com/v1/artists/053q0ukIDRgzwTr4vNSwab",
          "id": "053q0ukIDRgzwTr4vNSwab",
          "name": "Grimes",
          "type": "artist",
          "uri": "spotify:artist:053q0ukIDRgzwTr4vNSwab"
        }
      ],
      "available_markets": [
        "AD",
        "AE",
        "AL",
        "AR",
        "AT",
        "AU",
        "BA",
        "BE",
        "BG",
        "BH",
        "BO",
        "BR",
        "BY",
        "CH",
        "CL",
        "CO",
        "CR",
        "CY",
        "CZ",
        "DE",
        "DK",
        "DO",
        "DZ",
        "EC",
        "EE",
        "EG",
        "ES",
        "FI",
        "FR",
        "GB",
        "GR",
        "GT",
        "HK",
        "HN",
        "HR",
        "HU",
        "ID",
        "IE",
        "IL",
        "IN",
        "IS",
        "IT",
        "JO",
        "JP",
        "KW",
        "KZ",
        "LB",
        "LI",
        "LT",
        "LU",
        "LV",
        "MA",
        "MC",
        "MD",
        "ME",
        "MK",
        "MT",
        "MX",
        "MY",
        "NI",
        "NL",
        "NO",
        "NZ",
        "OM",
        "PA",
        "PE",
        "PH",
        "PL",
        "PS",
        "PT",
        "PY",
        "QA",
        "RO",
        "RS",
        "RU",
        "SA",
        "SE",
        "SG",
        "SI",
        "SK",
        "SV",
        "TH",
        "TN",
        "TR",
        "TW",
        "UA",
        "US",
        "UY",
        "VN",
        "XK",
        "ZA"
      ],
      "external_urls": {
        "spotify": "https://open.spotify.com/album/7rhiEqTIsswhakIAfpq2tr"
      },
      "href": "https://api.spotify.com/v1/albums/7rhiEqTIsswhakIAfpq2tr",
      "id": "7rhiEqTIsswhakIAfpq2tr",
      "images": [
        {
          "height": 640,
          "url": "https://i.scdn.co/image/ab67616d0000b273f990b0093204f7829a6340a5",
          "width": 640
        },
        {
          "height": 300,
          "url": "https://i.scdn.co/image/ab67616d00001e02f990b0093204f7829a6340a5",
          "width": 300
        },
        {
          "height": 64,
          "url": "https://i.scdn.co/image/ab67616d00004851f990b0093204f7829a6340a5",
          "width": 64
        }
      ],
      "name": "Miss Anthropocene (Rave Edition)",
      "release_date": "2021-01-01",
      "release_date_precision": "day",
      "total_tracks": 11,
      "type": "album",
      "uri": "spotify:album:7rhiEqTIsswhakIAfpq2tr"
    },
    "artists": [
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/053q0ukIDRgzwTr4vNSwab"
        },
        "href": "https://api.spotify.com/v1/artists/053q0ukIDRgzwTr4vNSwab",
        "id": "053q0ukIDRgzwTr4vNSwab",
        "name": "Grimes",
        "type": "artist",
        "uri": "spotify:artist:053q0ukIDRgzwTr4vNSwab"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/0y42IQBDFigO5mmEd1bGQG"
        },
        "href": "https://api.spotify.com/v1/artists/0y42IQBDFigO5mmEd1bGQG",
        "id": "0y42IQBDFigO5mmEd1bGQG",
        "name": "i_o",
        "type": "artist",
        "uri": "spotify:artist:0y42IQBDFigO5mmEd1bGQG"
      },
      {
        "external_urls": {
          "spotify": "https://open.spotify.com/artist/4aKdmOXdUKX07HVd3sGgzw"
        },
        "href": "https://api.spotify.com/v1/artists/4aKdmOXdUKX07HVd3sGgzw",
        "id": "4aKdmOXdUKX07HVd3sGgzw",
        "name": "Rezz",
        "type": "artist",
        "uri": "spotify:artist:4aKdmOXdUKX07HVd3sGgzw"
      }
    ],
    "available_markets": [
      "AD",
      "AE",
      "AL",
      "AR",
      "AT",
      "AU",
      "BA",
      "BE",
      "BG",
      "BH",
      "BO",
      "BR",
      "BY",
      "CH",
      "CL",
      "CO",
      "CR",
      "CY",
      "CZ",
      "DE",
      "DK",
      "DO",
      "DZ",
      "EC",
      "EE",
      "EG",
      "ES",
      "FI",
      "FR",
      "GB",
      "GR",
      "GT",
      "HK",
      "HN",
      "HR",
      "HU",
      "ID",
      "IE",
      "IL",
      "IN",
      "IS",
      "IT",
      "JO",
      "JP",
      "KW",
      "KZ",
      "LB",
      "LI",
      "LT",
      "LU",
      "LV",
      "MA",
      "MC",
      "MD",
      "ME",
      "MK",
      "MT",
      "MX",
      "MY",
      "NI",
      "NL",
      "NO",
      "NZ",
      "OM",
      "PA",
      "PE",
      "PH",
      "PL",
      "PS",
      "PT",
      "PY",
      "QA",
      "RO",
      "RS",
      "RU",
      "SA",
      "SE",
      "SG",
      "SI",
      "SK",
      "SV",
      "TH",
      "TN",
      "TR",
      "TW",
      "UA",
      "US",
      "UY",
      "VN",
      "XK",
      "ZA"
    ],
    "disc_number": 1,
    "duration_ms": 195300,
    "explicit": false,
    "external_ids": {
      "isrc": "GBAFL2000476"
    },
    "external_urls": {
      "spotify": "https://open.spotify.com/track/0LwScqPc3ALwZtOPW65ITG"
    },
    "href": "https://api.spotify.com/v1/tracks/0LwScqPc3ALwZtOPW65ITG",
    "id": "0LwScqPc3ALwZtOPW65ITG",
    "is_local": false,
    "name": "Violence - REZZ Remix",
    "popularity": 62,
    "preview_url": "https://p.scdn.co/mp3-preview/f0f271fc331d9560969053bb3d33bf725f94bc91?cid=fa0722f4a44a4bea92a42c424013dcba",
    "track_number": 4,
    "type": "track",
    "uri": "spotify:track:0LwScqPc3ALwZtOPW65ITG"
  },
  "currently_playing_type": "track",
  "actions": {
    "disallows": {
      "resuming": true,
      "skipping_prev": true
    }
  },
  "is_playing": true
}

function current_endpoint(args) {
  return new Promise(()=>{
    return response_data;

  })
}
