name: sound_wave_bot CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    env:
      BOT_USERNAME: sound_wave_bot
      CHANNEL_NAME: wonkmart
      OAUTH_TOKEN: ${{secrets.OAUTH_TOKEN}}
      SPOTIFY_CLIENT_ID: ${{secrets.SPOTIFY_CLIENT_ID}}
      SPOTIFY_SERVER_ID: ${{secrets.SPOTIFY_SERVER_ID}}
      REDIRECT_URI: ${{secrets.REDIRECT_URI}}
    steps:
    - name: do the first thing
      uses: actions/checkout@v2

    - name: install deps
      run: npm install

    - name: run the server
      run: pm2 restart server --update-env
