name: sound_wave_bot CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: do the first thing
      uses: actions/checkout@v2
    - name: build
      run: yarn && yarn build
    - name: give files a nice home
      run: cp -r build/* /home/sound_wave_bot/web
