name: sound_wave_bot CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: do the first thing
      uses: actions/checkout@v2

    - name: install deps
      run: npm install

    - name: run the server
      run: source ./.env && pm2 restart server

