name: sound_wave_bot CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: do the first thing
      uses: actions/checkout@v2
    - name: test
      run: touch big_booty
